### ISSUE TITLE
Review profili team

### ISSUE THREAD

**Issue by cloudify** [teamdigitale/teamdigitale.governo.it#112]

**Comment by spiunno** [comment]
Sul sito vecchio ogni pagina col CV terminava con 4 righe:
Data inizio:  xxx
Periodo previsto: fino al xxx
Compenso su base annua:  € xxx
Registrazione in Corte dei Conti:  xxx
Immagino fossero lette da una tabella?
Durante la migrazione queste voci sono andate perse e vanno recuperate urgentemente.

**Comment by cloudify** [comment]
Fixed by PR #131
