### ISSUE TITLE
ipotesi restyling home page del sito

### ISSUE THREAD

**Issue by sbronzolo** [teamdigitale/teamdigitale.governo.it#118]
Ipotesi di restyling della hp del sito Team trasformazione digitale per migliorare questi aspetti: 
1. far capire immediatamente cosa fa il team, con uno statement iniziale
2. offrire una vista "real time" delle attività del team
3. presentare e descrivere i progetti (di pari passo con la creazione della relativa sezione)
Nel nuovo menù saranno inserite anche le voci "progetti" e "contatti"
4. integrare elementi delle issue di 240, 241 e 242 (speciale, calendario, timeline)

Qui il low fi della pagina
https://app.moqups.com/giovanni@teamdigitale.governo.it/aHGppA49SB/edit/page/a2e7f2086

Statement approvato "Innovazione digitale per i cittadini e per lo sviluppo del Paese"
Possibili statement alternativi
Innovazione digitale per lo sviluppo del Paese
Costruiamo nuovi servizi pubblici digitali, partendo dalle basi
Costruiamo servizi pubblici migliori, grazie alla tecnologia
Nuovi servizi digitali per lo sviluppo del Paese

**Comment by cloudify** [comment]
@sbronzolo cosa manca qui per procedere?

**Comment by matteodesanti** [comment]
Pianificatoa per lunedì 13.11
