### ISSUE TITLE
Publish task should keep group of files as www-data

### ISSUE THREAD

**Issue by cloudify** [teamdigitale/teamdigitale.governo.it#141]
This is required to allow multiple users to deploy the site.

Currently the rsync script will set the group of files to the logged in user.

**Comment by rasky** [comment]
@cloudify this is how we fixed it on developers.italia.it: https://github.com/italia/developers.italia.it/blob/master/Makefile#L6. Given the very simple deploy model we want to keep, it's probably the best short-term solution.

**Comment by alranel** [comment]
Moving to GitHub Pages, this is no longer necessary
