### ISSUE TITLE
Pagina che descrive chi siamo

### ISSUE THREAD

**Issue by rasky** [teamdigitale/teamdigitale.governo.it#145]
Mi fanno notare da Facebook che nel nostro sito manca una pagina che spiega cos'è il Team Digitale, quando e da chi è stato istituito (con quale DPCM), quali sono gli obiettivi, ecc. Mi sembra che queste informazioni ci fossero nel vecchio sito @cloudify? /cc @sbronzolo

**Comment by cloudify** [comment]
Fixato settimana scorsa da #147
