### ISSUE TITLE
Menu off canvas dello slim header per mobile view

### ISSUE THREAD

**Issue by cloudify** [teamdigitale/teamdigitale.governo.it#151]
Come sul sito del piano triennale

**Comment by vito80ba** [comment]
Il sito del team prevede una collocazione diversa dell'hamburger icon, così come la sua gestione. 
Mentre sul sito del Piano Triennale (e gli altri sviluppati dal team) l'hamburger icon principale si presenta a sinistra con apertura off-canvas a sinistra, mentre lo slimheader lo tiene a destra con apertura a destra.
Come allineare i due design e quindi l'implementazione?
Necessario consiglio / bozza di @matteodesanti

**Comment by matteodesanti** [comment]
related to #152

**Comment by matteodesanti** [comment]
Si, serve una analisi "si sistema" per una soluzione condivisa. La mia idea è di aprire quel menu in dropdown, ma devo testare un po' di cose. Teniamola in blocked per ora.
