### ISSUE TITLE
new template

### ISSUE THREAD

**Issue by matteodesanti** [teamdigitale/teamdigitale.governo.it#152]
Porting del template di http://developers.italia.it basato su https://italia.github.io/ita-web-toolkit/

**Comment by cloudify** [comment]
Aggiungo anche @sbronzolo , è ancora relevant?

**Comment by cloudify** [comment]
È un duplicato di https://github.com/italia/design-jekyll-theme/issues/1 ?

cc @ruphy

**Comment by vito80ba** [comment]
Alcuni dubbi:
- menu di navigazione. Al click sui progetti si pare una breve lista di progetti più "In vista" e poi con la voce "tutti i progetti" si visualizza pagina di lista. Anche per TeamDigitale deve essere così? Quali sono i progetti "in vista"? @sbronzolo 
-  in alto a destra (su Developers) è presente un input form che permette autocomplete/ricerca per i progetti presenti nel sito. Devo riportarlo pari pari anche sul sito del Team? @matteodesanti @cloudify 
- pagina progetto: sul sito del team è presente l'aggancio delle "persone del team" coninvolte. Lascio così? e se sì come le mostro nel layout? @matteodesanti @sbronzolo

**Comment by vito80ba** [comment]
in attesa del design di @matteodesanti

**Comment by ruphy** [comment]
@cloudify no, direi che non è un duplicato (scusa per il delay, si è perso tra milioni di notifiche)

**Comment by matteodesanti** [comment]
@vito80ba In arrivo col design della pagina progetto e della home. Lunedì ;-)
