### ISSUE TITLE
Add additional social networks' buttons to the header area

### ISSUE THREAD

**Issue by gvarisco** [teamdigitale/teamdigitale.governo.it#155]
We should add the following social networks to our header area:

- GitHub (prio 1)
- Behance (prio 1)
- SlideShare (prio 2)
- SpeakerDeck (prio 2)

**Comment by cloudify** [comment]
@matteodesanti @sbronzolo direi eventualmente di incorporare questa richiesta nel nuovo design e chiudere questa issue intanto, che ne dite?

**Comment by sbronzolo** [comment]
Possiamo etichettarla redesign o qualcosa del genere in modo da identificare e separare la cosiddetta fase 2

Inviato da iPhone
