### ISSUE TITLE
Completamento pagine progetti

### ISSUE THREAD

**Issue by sbronzolo** [teamdigitale/teamdigitale.governo.it#171]
Se vogliamo rispettare scadenza sito vers. 2 entro luglio bisogna inviare asap pagina progetto a ciascun membro del team e chiedere completamento direttamente su github entro giovedì
Segnalare di fare la pagina come quella "developers" in modo da dare riferimento chiaro (inviare path). Non avendo riferimenti chiari, Raffa ha giustamente inviato pagina del progetto daf su drive, ma questo complica il processo e crea duplicazione di contenuti già scritti.

**Comment by cloudify** [comment]
Obsolete
