### ISSUE TITLE
Pagina blog sito - inserimento data pubblicazione post

### ISSUE THREAD

**Issue by simonesurdi** [teamdigitale/teamdigitale.governo.it#180]
@cloudify @sbronzolo nella pagina blog del sito diego chiede se i titoli dei post non riportano la data tranne quello sul piano triennale, perché lì la data era stata inserita nel sottotitolo del post. Come possiamo fare in modo che tutti i titoli dei post riportino la data?

**Comment by cloudify** [comment]
Duplicate of #293
