### ISSUE TITLE
Aggiornamenti necessari su pagina "Chi siamo"

### ISSUE THREAD

**Issue by gvarisco** [teamdigitale/teamdigitale.governo.it#205]
La pagina "Chi siamo" (sia in IT che EN) del sito web va aggiornata per archiviare i profili delle persone che hanno terminato il mandato. Nell'ultima riunione si menzionava l'idea di inserire tali profili in una sottocategoria della pagina, ad es. "Hanno collaborato con noi / Ringraziamo per la loro collaborazione:"

**Comment by sbronzolo** [comment]
Bisogna introdurre un attributo "Responsabile" / "Ha partecipato

**Comment by cloudify** [comment]
@sbronzolo cosa manca qui per procedere?

**Comment by sbronzolo** [comment]
Va introdotto un attributo al profilo, in modo da collocarlo automaticamente nella lista 1 (membro del team / responsabile ) e nella lista 2 (hanno collaborato / Ha collaborato).  Questa distinzione deve essere visibile sia nella pagina progetto sia nel chi siamo

**Comment by matteodesanti** [comment]
Good: ne terrò conto nel redesign.
