### ISSUE TITLE
Avoid caching of assets (css, js)

### ISSUE THREAD

**Issue by stefbaldipr** [teamdigitale/teamdigitale.governo.it#221]
Il caching del CSS può comportare problemi di visualizzazione per stylesheet non aggiornato lato client.

**Comment by cloudify** [comment]
Problema relativo anche a JS (e in genere a tutti gli asset statici).

Da controllare anche la configurazione degli header che abbiamo in nginx

**Comment by vito80ba** [comment]
Fatto. E' stata inserita, in coda alle risorse statiche una querystring con la data di build così da ovviare al caching.
