### ISSUE TITLE
meta tag description e og:description

### ISSUE THREAD

**Issue by matteodesanti** [teamdigitale/teamdigitale.governo.it#222]
Inserire i gli attributi nelle varie pagine.
Oggi i tag vengono generati secondo questa logica
```{% assign seo_description = page.description | default: page.excerpt | default: site.description[page.lang] %}```

**Comment by cloudify** [comment]
@matteodesanti puoi spiegare meglio cosa c'è da fare qua?

**Comment by matteodesanti** [comment]
Sì, serve verificare le description per le varie pagine.
Oggi il plugin per la seo usa la variabile `description:` valorizzata nei meta di pagina (il "Front Matter"). Se non la trova usa un excerpt autogenerato. Occorre secondo me un passaggio con la Google Search Console (per cui chiederei a @sbronzolo ) e in caso intervenire sui signoli file mk.
