### ISSUE TITLE
Creare calendario eventi pubblici del team

### ISSUE THREAD

**Issue by sbronzolo** [teamdigitale/teamdigitale.governo.it#240]
Creare calendario eventi pubblici del team. 

Il calendario ospita una lista di prossimi eventi del sito. Potrebbe essere alimentato da un Google spreadsheet gestito da chi gestisce gli eventi e sa identificare quali di questi eventi sono a) pubblici e b) rilevanti. 

Ad esempio al momento la lista potrebbe essere la seguente
https://docs.google.com/spreadsheets/d/1Ovspt2kGRNRNzZ4a-IEsvNp2-K4BAhHEJmnKLnhvE7I/edit#gid=0

Ipotesi campi
Titolo evento
Titolo panel/evento specifico
Coordinate googlemap
Link a profili team coinvolti (se tutto il team, link a pagina "chi siamo")
Link esterno a "scheda" evento su sito organizzatore

**Comment by sbronzolo** [comment]
@ludopoggi

**Comment by ludopoggi** [comment]
[Primo draft](https://docs.google.com/spreadsheets/d/1Ovspt2kGRNRNzZ4a-IEsvNp2-K4BAhHEJmnKLnhvE7I/edit#gid=0)

@sbronzolo

**Comment by cloudify** [comment]
@sbronzolo cosa manca qui per procedere?

**Comment by sbronzolo** [comment]
Faremo uno sprint a gennaio 

Inviato da iPhone
