### ISSUE TITLE
Ipotesi creare timeline con le milestone (highlights)

### ISSUE THREAD

**Issue by sbronzolo** [teamdigitale/teamdigitale.governo.it#241]
Creare una timeline del team, un po' come quella di un singolo progetto. 
Può essere un oggetto interessante da collocare in home page? 

Una possibile idea è fare degli highlights corredati da foto, video o citazioni 
https://docs.google.com/document/d/1em48JTcCDkB5Q0R4vmVjnx8O_HSd_6mJwLh6FfHEE5g/edit#heading=h.kv91ixyw6o42

Nota 1
In questo modo si assolve anche alla idea di usare anche i video, ma solo una selezione, sul nostro sito. Se ci fosse necessità, altri video possono sempre essere embeddati nella scheda progetto

Nota 2
In questo scenario la timeline avrebbe relativamente poche milestone e non sarebbe un mashup delle timeline di progetto

**Comment by filippomadoi** [comment]
https://docs.google.com/presentation/d/1rp7uutqWhEutleORuTLzeBNDJXDqKqHgGcJnCBe9fSo/edit#slide=id.g27aeb16dc2_0_0

**Comment by cloudify** [comment]
@sbronzolo cosa manca qui per procedere?
