### ISSUE TITLE
Variante template per "speciali" e banner per home page

### ISSUE THREAD

**Issue by sbronzolo** [teamdigitale/teamdigitale.governo.it#242]
Introdurre nel sito del team il concetto di speciali in termini di:

* inserimento di una modalità di evidenziazione di un contenuto speciale (banner- fascione o altro)

* creazione di un template di pagina che sia una sorta di mini home page (apertura con forte enfasi, testo)

**Comment by cloudify** [comment]
@sbronzolo cosa manca qui per procedere?

**Comment by matteodesanti** [comment]
Per l'affaccio in home degli speciali ho le idee chiare. Mi servirebbe invece una indicazioni di massima che contenuti fanno comodo in uno speciale. Magari @sbronzolo l'hai già fatto?
