### ISSUE TITLE
Nuova Twitter feed da embeddare nella pagina Innovation7

### ISSUE THREAD

**Issue by gditom** [teamdigitale/teamdigitale.governo.it#260]
Widget:

                       <a class="twitter-timeline"  href="https://twitter.com/search?q=g7%20OR%20%23innovation7%20list%3AITdigitalteam%2Fi-7-innovators" data-partner="tweetdeck"data-widget-id="914127569477406720">Tweet riguardo g7 OR #innovation7 list:ITdigitalteam/i-7-innovators</a>
            <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

**Comment by stefbaldipr** [comment]
done
