### ISSUE TITLE
Include twitter, ipress e medium nelle pagine progetto. fruibilità da mobile

### ISSUE THREAD

**Issue by sbronzolo** [teamdigitale/teamdigitale.governo.it#288]
Nelle pagine progetto ci sono widget con barra di scorrimento
- twitter
- metabase
- ipress

La fruibilità da mobile mi pare bassa, seguono considerazioni:

* O modifichiamo la UI oppure limitiamo il numero di item in ciascun box in modo da ridurre la quantità di scroll che fa perdere di fruibilità alla pagina  

* Per quanto riguarda Tirtter e ipress direi che Non serve affatto avere così tanti item, basta l'ultimo Tweet, l'ultimo comunicato stampa

* Per quanto riguarda Metabase la situazione diversa. Io nella mia testa avevo include separati, quindi un widget per ogni grafico

@matteodesanti  che ne pensi?

**Comment by cloudify** [comment]
vedere anche #321

**Comment by cloudify** [comment]
@matteodesanti abbiamo bisogno di tuo feedback

**Comment by matteodesanti** [comment]
Si, anche per me twitter e ipress direi li teniamo più asciutti.
Mentre per metabase serve che siano inclusi i singoli grafici, e serve farne la formattaizone a manina nel codice.
Inizio il redesign dalla scheda-progetto che è la più importante.
E' schedulato per il 13.11
