### ISSUE TITLE
Aggiungere data di aggiornamento a ogni pagina del sito web

### ISSUE THREAD

**Issue by gvarisco** [teamdigitale/teamdigitale.governo.it#293]
Va inserito 'Aggiornato a $data' in ogni pagina del sito web.

**Comment by cloudify** [comment]
Duplicates #180

**Comment by vito80ba** [comment]
1) Va inserito 'Aggiornato a $data' in ogni pagina del sito web.
Con una implementazione del genere avremmo tutte le pagine con la stessa data (ovvero quella di build). E' davvero questo il risultato che vogliamo?
2) (180) Data nel blog post, subito dopo la descrizione (come ora sul post "Piano triennale racconato ai fornitori...")
