### ISSUE TITLE
Ristrutturare pagine progetti, WHYs

### ISSUE THREAD

**Issue by gvarisco** [teamdigitale/teamdigitale.governo.it#298]
Ristrutturare pagine progetti inserendo alla fine di "In Breve" due righe: 
- Benefici per il cittadino
- Benefici per la Pubblica Amministrazione

**Comment by sbronzolo** [comment]
Verificare se questa struttura vale per i progetti meno maturi

**Comment by cloudify** [comment]
@sbronzolo cosa manca qui per procedere?
