### ISSUE TITLE
Analizzare Widget twitter sezione contatti

### ISSUE THREAD

**Issue by sbronzolo** [teamdigitale/teamdigitale.governo.it#303]
Creare un widget twitter che faccia mashup dei contenuti degli account del team / delle persone del team. In questo caso sostituirebbe il widget attuale

Esisteva una lista degli account del team
https://twitter.com/teamdigitaleIT/lists/team-digitale

Bisogna/si può introdurre, partendo da una lista, un filtro basato su hashtag / tag?

**Comment by gditom** [comment]
No, terrei il widget attuale nella sezione contatti, in quanto la lista comprende inevitabilmente anche tweet "personali" su argomenti che non siano il Team. E non esistono hashtag o singole parole per filtrare i tweet relativi ai contenuti del Team.
