### ISSUE TITLE
Analizzare widget twitter di ogni singolo progetto

### ISSUE THREAD

**Issue by sbronzolo** [teamdigitale/teamdigitale.governo.it#305]
Se il progetto ha account si usa account del progetto
Altrimenti si usa account del team o lista dei membri del team, filtrata per "hashtag" del progetto.

**Comment by gditom** [comment]
Controllati tutti. Unico mancante, come avevo già segnalato nella issue  #279 

Progetto "Piano trasformazione digitale"
inserire questo widget:
https://twitter.com/settings/widgets/new/search?query=pianotriennale%20list%3AteamdigitaleIT%2Fteam-digitale

@vito80ba
