### ISSUE TITLE
[sito ANPR] Ticker/banner con link a pagina progetto team

### ISSUE THREAD

**Issue by sbronzolo** [teamdigitale/teamdigitale.governo.it#310]
Ipotesi di lavoro 
https://app.moqups.com/giovanni@teamdigitale.governo.it/T0TmEwKUvF/view

**Comment by sbronzolo** [comment]
Inserire testo che spiega la gestione da parte del team

**Comment by sbronzolo** [comment]
Dal 2017 il progetto ANPR è coordinato dal Team per la trasformazione digitale. Per seguire i lavori e vedere lo stato di avanzamento vai alla scheda progetto

**Comment by cloudify** [comment]
Questa issue non è relativa al sito del team, ma al sito ANPR, probabilmente va spostata su https://github.com/italia/anpr
