### ISSUE TITLE
Dashboards: try to change font and contrast in metabase. 

### ISSUE THREAD

**Issue by giux78** [teamdigitale/teamdigitale.governo.it#314]
Dashboards: try to change font and contrast in metabase.

**Comment by cloudify** [comment]
Questo è da fare nel sito o dentro Metabase?

**Comment by giux78** [comment]
Dentro metabase credo.

**Comment by cloudify** [comment]
Ok allora apri una issue nel vostro Jira e chiudi questa?

Inviato da iPhone

**Comment by cloudify** [comment]
Puoi mettere un link alla story su Jira per reference?
