### ISSUE TITLE
Spostiamo la pagina di default a “Missione”

### ISSUE THREAD

**Issue by cloudify** [teamdigitale/teamdigitale.governo.it#320]
Spostiamo la pagina di default a “Missione” con un link a Progetti (non importa se c’è anche nel navigation bar). Posizionare il link ai Progetti sotto il link “Il Manifesto…..“. 

Eliminare il link “Attività” perchè si confonde con “Progetti” e non serve più allo scopo originario

**Comment by FlorianaF** [comment]
Una volta pronta, testa anche via mobile, ma bene anche tramite simulatori.

**Comment by FlorianaF** [comment]
Target date:  immediata. 13/10/2017

**Comment by sbronzolo** [comment]
Concordata altra modifica alla home page (inserimento statement)
