### ISSUE TITLE
Profilo Elisabetta

### ISSUE THREAD

**Issue by cloudify** [teamdigitale/teamdigitale.governo.it#324]
### Expected behavior

Profilo Elisabetta esiste in inglese e italiano

### Actual behavior

Profilo Elisabetta non esiste

### Steps to reproduce the behavior

Nella pagina [chi siamo](https://teamdigitale.governo.it/it/47-content.htm) e [About us](https://teamdigitale.governo.it/en/49-content.htm) deve esserci Elisabetta nella lista

**Comment by BettaPiq** [comment]
Bio italiana in fase di approvazione

**Comment by sbronzolo** [comment]
grazie @BettaPiq Quando sei pronta con il testo italiano lo carichiamo insieme
L'inglese dopo, quello lo fai da sola :)

**Comment by cloudify** [comment]
@sbronzolo ho fatto il merge ma la foto di profilo è portrait per cui viene tipo "santino" :) ora @BettaPiq la taglia quadrata e fa una nuova PR

**Comment by cloudify** [comment]
<img width="443" alt="chi_siamo_-_team_per_la_trasformazione_digitale" src="https://user-images.githubusercontent.com/48206/31670737-8fb71b6c-b358-11e7-8967-9c57fffd3d93.png">

**Comment by cloudify** [comment]
Ok con PR #342 abbiamo completato il profilo in Italiano di @BettaPiq , il profilo è stato mergiato in `development`

**Comment by cloudify** [comment]
@BettaPiq  ci pensi tu alla traduzione all'inglese?

**Comment by BettaPiq** [comment]
@cloudify fatta PR!
