### ISSUE TITLE
Statement nella home

### ISSUE THREAD

**Issue by sbronzolo** [teamdigitale/teamdigitale.governo.it#331]
### Expected behavior
1. Inserire fascia apertura home page sito con statement
**Innovazione digitale per i cittadini e per lo sviluppo del Paese**
+ link "Per saperne di più" che rimanda a sezione "Missione"
https://app.moqups.com/giovanni@teamdigitale.governo.it/aHGppA49SB/view

2.Chiudere voce di menù blog
3. Inserire voce di menù home, accesa

**Comment by cloudify** [comment]
@matteodesanti questa story è bloccata in attesa di design

**Comment by matteodesanti** [comment]
Così su desktop 
![home_-_team_per_la_trasformazione_digitale](https://user-images.githubusercontent.com/8171284/32097010-745dc002-bb08-11e7-9c5e-f022a96606d0.jpg)

**Comment by cloudify** [comment]
[pubblicato live](https://circleci.com/workflow-run/d5ea9219-be4c-4ae2-b7da-80d2f5f69d5f)

chiudo la issue o lascio aperta per la versione in inglese?
