### ISSUE TITLE
Nuovo sito, valutare cosa fare delle foto profilo

### ISSUE THREAD

**Issue by sbronzolo** [teamdigitale/teamdigitale.governo.it#332]
### Actual behavior
Attualmente si usa questo http://www.picturetopeople.org/photo_sketch/realistic_pencil_sketch_photo_effect.html
Caricare la propria foto possibilmente su sfondo bianco o chiaro, ideale sarebbe scontornata su fondo bianco 
Con queste impostazioni di setting, salvo adattamenti
<img width="374" alt="schermata 2017-10-16 alle 18 20 33" src="https://user-images.githubusercontent.com/24827270/31623118-c08b7d88-b29e-11e7-9de8-817c4fc7f229.png">

**Comment by cloudify** [comment]
@sbronzolo qual'è lo stato di questa issue? abbiamo materiale per procedere?

**Comment by matteodesanti** [comment]
Per lo stile eviterei bianconero o effetti strani. Massimo un filtro leggero per armonizzare gli stili.
Per le foto profilo userei senza dubbio quella di linkedin, così evitiamo di perdere tempo a procurarcele. Forse esagerato pensare ad usare le API di linkedin, ma ci risparmieremmo lo sbatto. QUanto a layout lo ridisegnerò per  il nuovo sito, magari partendo da https://developers.italia.it/it/chi-siamo ma forse no, magari meglio una griglia quadrata: siamo in tanti. Che ne pensate?
