### ISSUE TITLE
Ipotesi apertura canale YT di team

### ISSUE THREAD

**Issue by sbronzolo** [teamdigitale/teamdigitale.governo.it#333]
### Expected behavior
Ipotesi di creare canale YT
* Video proprietari del team, o comunque video di cui il team ha diritti, hanno il primo luogo di pubblicazione su YT
* Possibilità di creare playlist di video consigliati dal team

### Steps to reproduce the behavior
Attendere produzione nuovi contenuti video del team in modo da avere materiale fresco e di qualità per lanciare il canale. Nel frattempo eventuali necessità di embed di video possono essere risolte embeddando nostri video già caricati su Twitter

**Comment by cloudify** [comment]
@sbronzolo che facciamo di questa issue? la chiudiamo? o abbiamo materiale per procedere?

**Comment by sbronzolo** [comment]
Il canale verrà aperto non a breve ma nei prossimi mesi
Possiamo chiuderla

Inviato da iPhone
