### ISSUE TITLE
Accesso a github del team digitale da parte di tutti i membri del team

### ISSUE THREAD

**Issue by sbronzolo** [teamdigitale/teamdigitale.governo.it#338]
### Expected behavior
Tutti dovrebbero poter essere "assegnati" a una issue e potere gestire una PR (cosa che implica ad esempio  inserire asset come foto, ecc.)

Il problema ad esempio è che non possiamo assegnare issue a Ludovico, Elisabetta.
Elisabetta ha provato a inserire image ma non può farlo

**Comment by cloudify** [comment]
Invitati entrambi, devono accettare l'invito
