### ISSUE TITLE
ANPR manca la roadmap

### ISSUE THREAD

**Issue by sbronzolo** [teamdigitale/teamdigitale.governo.it#345]
### Expected behavior
Presenza della roadmap ANPR sulla scheda progetto
https://teamdigitale.governo.it/it/projects/anpr.htm

**Comment by luca-teamdigitale** [comment]
La roadmap sulla pagina di ANPR non ha senso.

**Comment by sbronzolo** [comment]
@luca-teamdigitale non mettete a disposizione dei Comuni nulla? Non fate azioni per favorire l'adesione? Se guardi le roadmap degli altri progetti, vedrai che non serve mettere milestone epocali.
