### ISSUE TITLE
Profilo Luca Bigliardi

### ISSUE THREAD

**Issue by simonesurdi** [teamdigitale/teamdigitale.governo.it#365]
Aggiornare profilo di Luca - dpcm è ritornato dalla corte dei conti.

1) togliere "new" label
2) inserire dettagli dpcm ita / eng

**Comment by simonesurdi** [comment]
@cloudify ho caricato le modifiche per luca per versione ita su branch development direttamente con commit mentre per versione eng con pull request per fusione su branch development. Se per voi non crea problemi potete mandare live su master? cc @sbronzolo

**Comment by cloudify** [comment]
@simonesurdi ho fatto merge su `development`, farò un deploy mercoledì, ok? intanto chiudo questa issue
