### ISSUE TITLE
Some minor Defects trovati nella pagina delle spese

### ISSUE THREAD

**Issue by FlorianaF** [teamdigitale/teamdigitale.governo.it#392]
build data 31/10/2017
Pagina delle spese del team:

- [x] 	“Dettaglio spese di sviluppo software e design superiori a EUR 30.000” Deve avere lo stessa dimensione del font di “Tipologia di spesa per macroarea”;
- [x]	Diminuire il font anche del titolo “Accordo con il ministero dell’interno per...”,  riportare questa fix su tutti gli altri accordi ;
- [x]	Diminuire font di  “Ministero dell’Interno per”,  riportare questa fix su tutti gli altri accordi ;
- [x]	Togliere “per ANPR” in “Ministero dell’Interno per ANPR” 
- [x]	Nella nota in  “* Compensi calcolati su base annua dei 21 Esperti del Team Digitale i cui Decreti del Presidente del Consiglio dei ministri della Repubblica Italiana (DPCM) sono registrati dalla Corte dei conti” deve essere aggiunta la frase “i pagamenti per gli esperti vengono emessi come stipendi mensili”
- [x] verificare la prima tabella su display 5.5'' come suggerito da @gvarisco .
Io credo che l'unica soluzione sia modificare il layout da colonna verticali a punti elenco quando su display molto piccoli.

**Comment by vito80ba** [comment]
Aggiungo: verificare la prima tabella su display 5.5'' come suggerito da @gvarisco .
Io credo che l'unica soluzione sia modificare il layout da colonna verticali a punti elenco quando su display molto piccoli.

**Comment by cloudify** [comment]
per questione mobile vedere #321

**Comment by vito80ba** [comment]
![localhost-4000-it-spese htm ipad pro 8](https://user-images.githubusercontent.com/1122389/32382324-30c961ae-c0b5-11e7-804d-3124efb59880.png)
![localhost-4000-it-spese htm iphone 6](https://user-images.githubusercontent.com/1122389/32382326-33be8100-c0b5-11e7-8208-6913147114e3.png)
