### ISSUE TITLE
Some isssues aperte durante la Review 

### ISSUE THREAD

**Issue by FlorianaF** [teamdigitale/teamdigitale.governo.it#394]
- [x] Versione mobile togliere la voce dello special "innovation7" nella prima pagina 
![image](https://user-images.githubusercontent.com/31762670/32319726-cfceaea8-bfbb-11e7-82b2-fdee98b9a39e.png)
- [x] Nella voce menù della versione mobile" Find out about the innovation 7" aggiungere "@G7"
- [x] Nella versione mobile nel menù aggiornare anche il link alle "spese del team" (solo nella versione mobile avremo due link per avere le info)
- [ ] Nella pagina home, mettere la data dell'aggiormento delle dashabord qualcosa del genere: 
![image](https://user-images.githubusercontent.com/31762670/32320037-b8b1a95e-bfbc-11e7-8dc0-a0c9a6515db6.png) (se è un'immagine mettere la data subito sotto)

**Comment by cloudify** [comment]
cc @matteodesanti @sbronzolo in caso vogliano aggiungere qualcosa

**Comment by matteodesanti** [comment]
@FlorianaF @cloudify per la data sul bottone, possiamo usare secondo voi la data della build che dovrebbe essere `{{ site.time | date: '%d/%m/%Y' }}`

**Comment by cloudify** [comment]
@matteodesanti ne parlavo con @vito80ba , il problema della data della build è che ad ogni release si aggiorna, anche se non è stato fatto nessun aggiornamento a quella pagina...

La questione della data di ultimo aggiornamento va affrontata in due modi diversi:

* la data di ultima modifica del file sorgente per le pagine statiche (es. l'homepage o la singola pagina di profilo)
* una gestione specifica per le pagine dinamiche: per esempio nella pagina del team con tutti i profili, andrebbe presa la data di "aggiunta" dell'ultimo profilo o la data di modifica del profilo che e' stato modificato piu' recentemente

di fatto il meccanismo dovrebbe funzionare con una data di default che e' il timestamp dell'ultima modifica di quel file, con la possibilita' di fare override in caso di pagine dinamiche

**Comment by FlorianaF** [comment]
5) @vito80ba togliere  la voce ( iva inclusa)
6) Nella lista di chi siamo, bisogna mettere: (xx/xx/xx - current)  mentre per David e Carlo (xx/xx/xx - xx/xx/xx)

**Comment by vito80ba** [comment]
![localhost-4000-it-47-content htm iphone 6 plus](https://user-images.githubusercontent.com/1122389/32387270-37011c92-c0c4-11e7-9c5b-a4972c82fa0c.png)
![localhost-4000-it-47-content htm ipad pro](https://user-images.githubusercontent.com/1122389/32387274-38feb2b6-c0c4-11e7-888b-6f215c0d8765.png)

**Comment by cloudify** [comment]
@vito80ba per Paolo Barberis, togli "ad oggi", poi troveremo una dicitura corretta ma per ora meglio non mettere niente piuttosto che "ad oggi"

**Comment by cloudify** [comment]
@vito80ba potresti marchiare i task fatti come done (i checkbox sono cliccabili), thx

**Comment by cloudify** [comment]
@matteodesanti @FlorianaF @vito80ba tra l'altro, se per data di aggiornamento delle dashboard si intende quelle incluse da Metabase via `iframe`, li non è possibile in modo facile mettere una data, perchè l'inclusione della dashboard viene fatta dal browser via `iframe`, mentre il sito nostro è statico.

**Comment by cloudify** [comment]
@vito80ba in attesa della #402 per fare le date di aggiornamento "corrette", metti pure la data dell'ultima build, come data di aggiornamento dei progetti nell'homepage
