### ISSUE TITLE
Benefici PagoPA

### ISSUE THREAD

**Issue by FlorianaF** [teamdigitale/teamdigitale.governo.it#413]
@giuseppevirgone 
Inserire nella pagina del progetto i benefici:

### Expected behavior

Benefici per la PA

Benefici per il cittadino

**Comment by giuseppevirgone** [comment]
Ecco:

Per i cittadini:

   -

   multicanalità integrata a livello nazionale con trasparenza dei costi
   delle commissioni, ovvero il cittadino dispone di più canali di pagamento
   possibili
   -

   uniformità dell'avviso cartaceo e possibilità di avvisare il cittadino
   digitalmente sui canali che preferisce (notifiche sull’app o sul sito del
   PSP scelto, SMS o mail)
   -

   certezza del debito dovuto, con possibilità di ottenere
   l'attualizzazione dell'importo (ovvero l’importo da pagare è sempre quello
   valido e richiesto dalla PA. Se l’importo varia nel tempo per interessi di
   mora o altro, su PagoPA viene sempre aggiornato)
   -

   semplicità e velocità del processo: basta inserire il codice di avviso
   (IUV Identificativo Unico Versamento) per pagare e ricevere la quietanza
   liberatoria ovvero la certezza che la PA ha incassato il tributo e non
   potranno esserci verifiche o accertamenti successivi.


Per le Pubbliche Amministrazioni:

   -

   riconciliazione automatica degli incassi
   -

   riduzione dei costi di transazione e processo
   -

   incasso delle somme D+1 (giorno lavorativo successivo al pagamento)
   direttamente sui conti di tesoreria
   -

   fornire più canali di incasso vuol dire incassare prima


Effetti nel breve periodo

Sono quelli esposti sopra e immediatamente visibili. Per il cittadino il
vantaggio immediato risiede nella possibilità di pagare scegliendo il
canale (online o offline) e il PSP preferito in base alle sue
considerazioni personali che vanno dall’esperienza utente fino al costo
della commissione di servizio che viene esposta in modo trasparente prima
del pagamento.

Per la PA il vantaggio risiede nello snellimento delle fasi di
riconciliazione delle somme incassate, che vengono rendicontate
automaticamente sui conti di tesoreria indicati, con risparmio di costi di
processo importanti e incassano a D+1 ovvero il giorno successivo al
pagamento. Questi risparmi, ovviamente variano da amministrazione ad
amministrazione.

Non ultimo, per diversi Enti soprattutto di piccole dimensioni, PagoPa
rappresenta innanzitutto l’opportunità per poter finalmente offrire
strumenti digitali di pagamento ai propri cittadini.


Effetti nel lungo periodo

La possibilità per il cittadino di scegliere il canale con cui pagare con
evidenza dei costi di commissione, mette in competizione tra loro i vari
soggetti PSP che erogano il servizio e apre a nuovi soggetti più
competitivi. A tendere, questa trasparenza porterà ad un livellamento verso
il basso delle commissioni e ad un miglioramento dell’esperienza utente.


Giuseppe Virgone

*Digital Payment*Twitter <https://twitter.com/giuvir1999> * Medium
<https://medium.com/@giuvir1999> * LinkedIN
<https://www.linkedin.com/in/giuseppe-virgone-0420a144>
·D *TEAM PER LA TRASFORMAZIONE DIGITALE*
*Presidenza del Consiglio dei Ministri*
teamdigitale.governo.it




2017-11-06 10:20 GMT+01:00 Floriana Ferrara <notifications@github.com>:

**Comment by giuseppevirgone** [comment]
Magari eliminerei gli effetti nel breve e lungo periodo lasciando solo
l'elenco puntato e numerato

Giuseppe Virgone

*Digital Payment*Twitter <https://twitter.com/giuvir1999> * Medium
<https://medium.com/@giuvir1999> * LinkedIN
<https://www.linkedin.com/in/giuseppe-virgone-0420a144>
·D *TEAM PER LA TRASFORMAZIONE DIGITALE*
*Presidenza del Consiglio dei Ministri*
teamdigitale.governo.it




Il giorno 6 novembre 2017 11:48, Giuseppe Virgone <
giuseppe@teamdigitale.governo.it> ha scritto:

**Comment by FlorianaF** [comment]
Aspetta altrimento devo fare un lavoro di merge tra tutte le email...mi
rimandi una precisa...di quello che vuoi mettere...togliento...la parte che
dicevi? Giusto per essere certa di cosa inserire.

COme puoi immaginare sono un attimo sotto pressione, non vorrei fare errori

Il giorno 6 novembre 2017 11:49, Giuseppe Virgone <notifications@github.com>
ha scritto:

**Comment by giuseppevirgone** [comment]
Ecco:

Per i cittadini:

   -

   multicanalità integrata a livello nazionale con trasparenza dei costi
   delle commissioni, ovvero il cittadino dispone di più canali di pagamento
   possibili
   -

   uniformità dell'avviso cartaceo e possibilità di avvisare il cittadino
   digitalmente sui canali che preferisce (notifiche sull’app o sul sito del
   PSP scelto, SMS o mail)
   -

   certezza del debito dovuto, con possibilità di ottenere
   l'attualizzazione dell'importo (ovvero l’importo da pagare è sempre quello
   valido e richiesto dalla PA. Se l’importo varia nel tempo per interessi di
   mora o altro, su PagoPA viene sempre aggiornato)
   -

   semplicità e velocità del processo: basta inserire il codice di avviso
   (IUV Identificativo Unico Versamento) per pagare e ricevere la quietanza
   liberatoria ovvero la certezza che la PA ha incassato il tributo e non
   potranno esserci verifiche o accertamenti successivi.


Per le Pubbliche Amministrazioni:

   -

   riconciliazione automatica degli incassi
   -

   riduzione dei costi di transazione e processo
   -

   incasso delle somme D+1 (giorno lavorativo successivo al pagamento)
   direttamente sui conti di tesoreria
   -

   fornire più canali di incasso vuol dire incassare prima


Giuseppe Virgone

*Digital Payment*Twitter <https://twitter.com/giuvir1999> * Medium
<https://medium.com/@giuvir1999> * LinkedIN
<https://www.linkedin.com/in/giuseppe-virgone-0420a144>
·D *TEAM PER LA TRASFORMAZIONE DIGITALE*
*Presidenza del Consiglio dei Ministri*
teamdigitale.governo.it




Il giorno 6 novembre 2017 11:51, Floriana Ferrara <notifications@github.com>
ha scritto:
