### ISSUE TITLE
I7-EN: aggiunta di video e doc "report I-7 Legacy"

### ISSUE THREAD

**Issue by vito80ba** [teamdigitale/teamdigitale.governo.it#435]
### Expected behavior
Per mettere in risalto i documenti pensavamo ad una sezione prima di news chiamata "The I-7 Legacy" che sotto fosse divisa in due: a sinistra (o destra) il video embeddato di youtube, dalla parte opposta l'immagine della prima pagina del report linkata al report stesso.
(by @simonesurdi )

### Actual behavior
Non esiste sezione video e doc

**Comment by cloudify** [comment]
possiamo chiudere questa?
