### ISSUE TITLE
Aggiornate pagina "Spese Team" al 30/11/2017

### ISSUE THREAD

**Issue by FlorianaF** [teamdigitale/teamdigitale.governo.it#438]
### Expected behavior
Deve essere aggiornata la pagina delle spese
### Steps to reproduce the behavior
Chiedere a Viviana di modificare il file xls, se non è stato fatto, e procedere con Vito con le modifche necessarie per il team

**Comment by cloudify** [comment]
Fixed by f77340834076aba9bd2e7dec09662b2d86e0a9af
