### ISSUE TITLE
Aggiungere profili giovanni ruggero, fabio fumarola e maria claudia (quando avremo la bio)

### ISSUE THREAD

**Issue by giux78** [teamdigitale/teamdigitale.governo.it#454]
### Expected behavior
Nella pagina chi siamo mostrare i profili di fabio, giovanni e maria claudia quando avremo la bio 

### Actual behavior
Non ci sono i profili

**Comment by cloudify** [comment]
@giux78 meglio creare tre issue separate e assegnare ognuna all'owner del profilo.

**Comment by giux78** [comment]
@cloudify  ok
