### ISSUE TITLE
Inserire video PagoPA embeddato all'interno del sito

### ISSUE THREAD

**Issue by simonesurdi** [teamdigitale/teamdigitale.governo.it#462]
Inserire video PagoPA embeddato all'interno del sito @giuseppevirgone

**Comment by gditom** [comment]
ecco il codice per l'embedd:

<blockquote class="twitter-video" data-lang="it"><p lang="it" dir="ltr">Un modo diverso e più semplice per i cittadini di pagare la Pubblica Amministrazione, più immediato ed economico per il Paese <a href="https://twitter.com/hashtag/PagoPA?src=hash&amp;ref_src=twsrc%5Etfw">#PagoPA</a> <a href="https://t.co/jayzc8mE0q">pic.twitter.com/jayzc8mE0q</a></p>&mdash; Team Digitale (@teamdigitaleIT) <a href="https://twitter.com/teamdigitaleIT/status/851377582457139200?ref_src=twsrc%5Etfw">10 aprile 2017</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by vito80ba** [comment]
Si sta predisponendo canale youtube, appena pronto posso creare embed

**Comment by gditom** [comment]
Ecco il video da embeddare: https://youtu.be/RHOAu5GwKnE
