### ISSUE TITLE
Aggiornamento pagina progetto SPID

### ISSUE THREAD

**Issue by simonesurdi** [teamdigitale/teamdigitale.governo.it#488]
Aggiornamento 1) contenuti, 2) roadmap, 3) team member attivi sul progetto

I team members che hanno partecipato al progetto ma non sono più membri del team devono essere spostati più in basso all'interno una sezione chiamata "Hanno contribuito"
 
@valeriopaolini cc @sbronzolo cc @vito80ba

**Comment by alessandrolinardi** [comment]
@valeriopaolini sarebbe da aggiungere la timeline del progetto sul sito, per quando riusciresti ad integrarla? Grazie
