### ISSUE TITLE
Aggiornamento pagina progetto Designers Italia

### ISSUE THREAD

**Issue by simonesurdi** [teamdigitale/teamdigitale.governo.it#491]
Aggiornamento 1) contenuti, 2) roadmap, 3) team member attivi sul progetto

I team members che hanno partecipato al progetto ma non sono più membri del team devono essere spostati più in basso all'interno una sezione chiamata "Hanno contribuito"
 
@matteodesanti  cc @sbronzolo cc @vito80ba

**Comment by francescozaia** [comment]
La roadmap è stata aggiornata abbastanza di recente, andrebbe soltanto integrata con un paio di punti sul nuovo UI-kit a cui stanno lavorando @nikorobins e @matteodesanti.

Team member: manchiamo io e Laura Bordin.
