### ISSUE TITLE
Responsabile "Media" nella sezione "progetti"

### ISSUE THREAD

**Issue by alessandrolinardi** [teamdigitale/teamdigitale.governo.it#521]
Nelle pagine dei vari progetti (ANPR, cittadinanza digitale etc.), aggiornare responsabile media
@vito80ba  cc @cloudify @simonesurdi

**Comment by simonesurdi** [comment]
@vito80ba ci sono novità su questa issue? cc @sbronzolo @cloudify @alessandrolinardi

**Comment by cloudify** [comment]
@vito80ba credo si parli dell'include `ipress.html`
