### ISSUE TITLE
Aggiornamento pagina progetto Developers

### ISSUE THREAD

**Issue by gditom** [teamdigitale/teamdigitale.governo.it#571]
Update roadmap per le linee guida riuso

**Comment by gditom** [comment]
Lasciare embedd video Hack Developers solo da YouTube e spostarlo dove ora è embeddato da Twitter

**Comment by gditom** [comment]
"Dal blog"
richiamare la feature page di Medium: https://medium.com/team-per-la-trasformazione-digitale/developers-italia/home

**Comment by gvarisco** [comment]
Video duplicato rimosso in ba223a5c31924ef329cd665392c70bc5013f7400
