### ISSUE TITLE
Refactoring Import da Medium

### ISSUE THREAD

**Issue by vito80ba** [teamdigitale/teamdigitale.governo.it#575]
Attualmente il plugin MediumIporter del sito del Team fa n.2 chiamate diverse a Medium per ottenere i feed dei post in "homepage" delle collezioni medium in Italiano e in inglese.
Per ogni post trovato, singolarmente, copia i dati necessari in una Jekyll Collection che viene messa in memoria.
Successivamente a questa operazione, ogni pagina che contiene riferimenti a post medium cicla a sua volta queste collezioni per poter impaginare i contenuti.
Con questa configurazione abbiamo un sito Jekyll che necessita di non meno di 70 secondi per poter partire.

Questo refactoring si rende necessario per poter implementare le nuove Medium Collection relative al "Club dei digitali virtuosi" e a "Developers Italia".

## Proposta 1
Utilizzare lo stesso metodo usato per il sito Developers nella parte "cosa fare". Ovvero una mera chiamata alle API medium e immagazzinare il json ottenuto in _data , quindi impaginare i post all'occorrenza lato client tramite Handlebars o Jquery.

## Proposta 2
Come per la proposta 1 fare una mera chiamata alle API medium e immagazzinare il json in _data e quindi processarlo lato server tramite jekyll-liquid.

Rif. #574 #573 #571

**Comment by cloudify** [comment]
Capisco il problema che sollevi, ma mi chiedo quale sia effettivamente l'obiettivo - vogliamo avere una KPI relativa al tempo di build? e che valore vogliamo dargli e perché?

@gditom vedi degli svantaggi ad avere un tempo di build di qualche minuto?

@sbronzolo @matteodesanti quali sono le implicazioni a livello di SEO della Proposta 1, ed è un qualcosa che ci interessa gestire?

@rasky ora stiamo usando delle VM free di CircleCI che non sono super performanti, magari possiamo pensare a qualcosa a pagamento per abbassare i tempi di build?
