### ISSUE TITLE
Modifica struttura pagina chi siamo (divisione lista esperti) 

### ISSUE THREAD

**Issue by francescomda** [teamdigitale/teamdigitale.governo.it#673]
### Expected behavior

Sulla [pagina chi siamo](https://teamdigitale.governo.it/it/chi-siamo) del sito del Team vogliamo dividere le liste degli esperti in due sezioni: sopra tutti gli esperti attivi, sotto quelli che hanno terminato la collaborazione con il Team. 
Il titolo della prima parte resta "Il Team"
Il titolo della seconda parte sarà "Hanno collaborato con noi"

**Comment by francescozaia** [comment]
Online:
- https://teamdigitale.governo.it/it/chi-siamo
- https://teamdigitale.governo.it/en/team

@francescomda a me sembra ok, puoi verificare anche tu che torni tutto?
