### ISSUE TITLE
Profilo Andrea Carlini

### ISSUE THREAD

**Issue by ErikaMiglietta** [teamdigitale/teamdigitale.governo.it#678]
Creazione profilo Andrea in ita e eng + foto

**Comment by axcarlin** [comment]
In allegato trovate :

1. Foto Profilo

**Comment by francescozaia** [comment]
Aggiungo per comodità l'immagine croppata quadrata e rinominata:
![andrea-carlini](https://user-images.githubusercontent.com/481084/54909942-9ecc9700-4eeb-11e9-9e1f-e454bf07b57e.jpg)

**Comment by axcarlin** [comment]
Ho fatto un fork
