### ISSUE TITLE
Embedding dei tweet per #hashtag

### ISSUE THREAD

**Issue by francescomda** [teamdigitale/teamdigitale.governo.it#722]
### Expected behavior

Sulle pagine di progetto (v. [ANPR](https://teamdigitale.governo.it/it/projects/anpr.htm)) non funziona l'embed dei tweet, che dovrebbe essere governato dagli hashtag (in questo caso il tag di riferimento è anpr, ma non ci sono tweet, nonostante solo pochi giorni fa sia stato fatto un tweet con hashtag #anpr). 

[L'unico embedding che funziona è Designers Italia](https://teamdigitale.governo.it/it/projects/designers.htm), dove però è embeddato un profilo twitter (designersITA). 

### Actual behavior

Non appaiono gli ultimi tweet nelle pagine di progetto.

**Comment by francescozaia** [comment]
Purtroppo Twitter da Set 2018 ha [deprecato la funzionalità di embed per ricerca o hashtag](embedding search timelines not working anymore: https://twittercommunity.com/t/deprecating-widget-settings/102295), temo vada fatto tramite API. Investigheremo.

**Comment by francescomda** [comment]
CIao @francescozaia, grazie della risposta ma cancello la issue perché proprio ieri abbiamo deciso di eliminare l'embed (proprio perché twitter ha deprecato). Faccio una PR appena ho un minuto libero!
