### ISSUE TITLE
Profilo Paolo Micozzi

### ISSUE THREAD

**Issue by ErikaMiglietta** [teamdigitale/teamdigitale.governo.it#728]
Creazione profilo Paolo Micozzi in ita e eng + foto

**Comment by paomico** [comment]
[Profilo Paolo Micozzi - ITA - vs01.docx](https://github.com/teamdigitale/teamdigitale.governo.it/files/2987839/Profilo.Paolo.Micozzi.-.ITA.-.vs01.docx)
[RM ENG Micozzi biografia.docx](https://github.com/teamdigitale/teamdigitale.governo.it/files/2987862/RM.ENG.Micozzi.biografia.docx)
![paolo_modify](https://user-images.githubusercontent.com/48281544/54680552-6d7a5280-4b0a-11e9-8e26-7a920caea199.jpg)
