### ISSUE TITLE
Profilo Marco Cipri

### ISSUE THREAD

**Issue by ErikaMiglietta** [teamdigitale/teamdigitale.governo.it#729]
Creazione profilo Marco Cipri in ita e eng + foto

**Comment by marcocipri** [comment]
Sono nato a Roma. Ho speso la mia infanzia e adolescenza rimettendo l'orologio con il cannone del Gianicolo e consumando le suole delle scarpe sui sanpietrini di Trastevere.
Come parte della mia generazione, sono stato corrotto in giovine età da quelle scatolette misteriose che erano i primi home computer e che avevano portato la magia nelle nostre camerette, trasformandole in cimiteri di joystick e musicassette a nastro…. le memorie di massa di allora.
Nel mentre resto fulminato da Guerre Stellari e Star Trek che mi convincevano che c'è sempre una missione quinquennale ( ma ci sono anche piani triennali) alla ricerca di altre forme di vita e di civiltà (tecnologie e piattaforme), fino ad arrivare la, dove nessun uomo (italiano) è mai giunto prima.
La curiosità di capire come funzionassero i computer mi ha portato a frequentare la facoltà di Ingegneria Informatica, facendo poi dell'informatico la mia professione ma rendendomi ancora più curioso.
Quando ho saputo che l'Enterprise del Team Digitale arruolava nuovi cadetti non ho potuto resistere e tutto d'un tratto mi ritrovo qui, a fare la mia parte per portare a velocità Warp il paese dove è nata e sta crescendo mia figlia.
Questo viaggio l'ho potuto iniziare grazie alla pazienza e sostegno di mia moglie ma anche grazie alla disponibilità della società dove lavoro, la Bwin Italia, che non solo ha condiviso il mio entusiasmo per questo progetto ma mi ha anche concesso un periodo di aspettativa, mettendomi in condizione di partecipare nel migliore dei modi a questa missione.
Che equipaggio fantastico!

![io](https://user-images.githubusercontent.com/5989506/54464811-7cfb4380-4778-11e9-81a1-89dd400d5de2.jpg)


Data inizio: 01 marzo 2019
 
Data fine: 15 settembre 2019
 
Compenso su base annua: € 75.000
 
Registrazione in Corte dei Conti: Il  decreto di nomina è in fase di registrazione presso la Corte dei Conti.

**Comment by francescozaia** [comment]
@marcocipri riesci a creare una Pull Request così possiamo approvarla e mergiarla? ([info](https://github.com/teamdigitale/teamdigitale.governo.it/wiki/Come-aggiungere-la-propria-bio-al-sito))
