### ISSUE TITLE
Elimina Twitter dai profili esperti

### ISSUE THREAD

**Issue by francescomda** [teamdigitale/teamdigitale.governo.it#767]
### Expected behavior

Vorrei togliere l'embedding degli ultimi tweet pubblicati da tutti gli esperti del team, come appare qui: 
https://teamdigitale.governo.it/it/people/luca-prete.html

**Comment by francescozaia** [comment]
Che ne facciamo dei progetti che embeddano le proprie timeline, come Designers o Developers?

**Comment by francescomda** [comment]
Mettiamo i link anche su quelli, faccio io la PR

**Comment by francescozaia** [comment]
Fatto io in #768
